locale: "en-US"
title: Joe Chan's Blog
url: "http://github.com/1030310877/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
google_analytics_key: ""

# Default description in social shares for the jekyll-seo-tag gem
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Author details for the jekyll-seo-tag gem
author:
  name: Joe Chan
  email: chenqiao921197@gmail.com
  twitter: # twitter username without the @ symbol

plugins:
  - jekyll-feed
# Social details for the jekyll-seo-tag gem
social:
  name: Strata Reloaded Template
  links:
    - https://github.com/comfusion/strata-reloaded-jekyll-template

permalink: pretty

rss: true

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-sitemap"

# Jekyll SEO Tag
webmaster_verifications:
  google: # 1234
  bing: # 1234
  alexa: # 1234
  yandex: # 1234

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
  
gitalk:
  enable: true    #是否开启评论
  clientID: 28cf53d945352304ffab                            
#生成的clientID
  clientSecret: 86c14e036bb28b1465d20416d6a4d122a700c50c    #生成的clientSecret
  repo: 1030310877.github.io    #仓库名称
  owner: 1030310877    #github用户名
  admin: 1030310877	
  distractionFreeMode: true #是否启用阴影遮罩
